# In config/build.yaml

---
include:
  - board: nice_nano_v2
    shield: quark_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: quark_right
