# In config/build.yaml

---
include:
  - board: nice_nano_v2 # IMPORTANT: Or pro_micro, seeed_xiao_ble, etc.
    shield: quark_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2 # IMPORTANT: Use the same board for the right half
    shield: quark_right